### ISSUE TITLE
服务离线

### ISSUE THREAD

**Issue by huxmhuxm** [ly1012/wiremock-ui#3]
我用docker拉取的wiremock的镜像，版本是2.35.1-1，然后使用docker部署了服务，但是在这个ui页面配置了http://ip:port  之后，提示我服务离线，是为什么呢，还需要配套修改wiremock的源码吗

**Comment by ly1012** [comment]
不需要修改源码，提示服务离线表示你当前的访问位置无法访问你指定的 WireMock 服务地址。我自己电脑上没有复现你说的问题，你在当前访问位置（自己电脑就在浏览器或 Postman 等工具）尝试调用下你的 WireMock 服务接口看下是否正常，比如：`http://localhost:8101/__admin/mappings?offset=0&limit=10`。

如果无法正常访问，可能是开了代理、协议类型错误（比如 http 写成了 https）、端口写错了等等。

**Comment by huxmhuxm** [comment]
> 不需要修改源码，提示服务离线表示你当前的访问位置无法访问你指定的 WireMock 服务地址。我自己电脑上没有复现你说的问题，你在当前访问位置（自己电脑就在浏览器或 Postman 等工具）尝试调用下你的 WireMock 服务接口看下是否正常，比如：`http://localhost:8101/__admin/mappings?offset=0&limit=10`。
> 
> 如果无法正常访问，可能是开了代理、协议类型错误（比如 http 写成了 https）、端口写错了等等。

之前我浏览器确实是可以访问wiremock的服务接口，但是本地起的这个项目不太行，不过我现在在本地重新部署了一套已经可以了，之前可能我哪里弄错了；试用了一下很好用，感谢！
